name: build and deploy
run-name: running deployment
on:
  push:
    branches:
      - main
    
permissions:
    id-token: write

env:
  DB_LOCATION: local
  REMOTE_SCHEMA: dev
  DB_LOGGING: off
#   this will work for test but not deploy. Need to figure out how to set different env vars for the deploy. And how to put the secrets (db/name and password) somewhere secret - pass in from Github secrets or from AWS secret manager

# also dockerfile should set up virtual environment

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v5
          
          - name: Install requirements
            run: pip install -r requirements.txt

          - name: Run tests
            run:  python3 -m pytest

    deploy:
       runs-on: ubuntu-latest
       needs: test
       steps:
          - name: Checkout
            uses: actions/checkout@v5

          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
            with:
              role-to-assume: arn:aws:iam::261219435789:role/github-actions-ecr-push-jbr
              aws-region: eu-west-2

          - name: Get Caller Identity
            run: aws sts get-caller-identity
        
          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a
            
          - name: Build, tag, and push docker image to Amazon ECR
            run: |
               docker build -t jbr-coins-api .
               docker tag jbr-coins-api:latest 261219435789.dkr.ecr.eu-west-2.amazonaws.com/jbr-coins-api:latest
               docker push 261219435789.dkr.ecr.eu-west-2.amazonaws.com/jbr-coins-api:latest
               echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
          
          - name: Render Amazon ECS task definition
            id: task-def
            uses: aws-actions/amazon-ecs-render-task-definition@v1
            with:
              task-definition: .github/workflows/task-definition.json
              container-name: coins-api-server
              image: ${{ steps.login-ecr.outputs.image }}
              # environment-variables: "LOG_LEVEL=info"
              # secrets: "SECRET_KEY=arn:aws:ssm:region:0123456789:parameter/secret"

          - name: Deploy to Amazon ECS service
            uses: aws-actions/amazon-ecs-deploy-task-definition@v2
            with:
              task-definition: ${{ steps.task-def.outputs.task-definition }}
              service: jbr-ecs-service
              cluster: jbr-cluster
              wait-for-service-stability: true
